### ISSUE TITLE
Error with Flow types and no-unused-vars

### ISSUE THREAD

**Issue by wcjohnson** [wcjohnson/lightscript#67]
```js
import { ESQuery } from './query'

class Clazz:
  createQuery(): ESQuery ->
    new ESQuery(this)
```

Crashes the linter with:

```
wcj-mac-20171:elasticsearch wcj$ $(yarn bin)/eslint src/backend.lsc
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at isForInRef (/Users/wcj/dev/ormojo/node_modules/eslint/lib/rules/no-unused-vars.js:410:24)
    at variable.references.some.ref (/Users/wcj/dev/ormojo/node_modules/eslint/lib/rules/no-unused-vars.js:447:21)
    at Array.some (<anonymous>)
    at isUsedVariable (/Users/wcj/dev/ormojo/node_modules/eslint/lib/rules/no-unused-vars.js:446:40)
    at collectUnusedVariables (/Users/wcj/dev/ormojo/node_modules/eslint/lib/rules/no-unused-vars.js:569:26)
    at collectUnusedVariables (/Users/wcj/dev/ormojo/node_modules/eslint/lib/rules/no-unused-vars.js:576:17)
    at Program:exit (/Users/wcj/dev/ormojo/node_modules/eslint/lib/rules/no-unused-vars.js:621:36)
    at listeners.(anonymous function).forEach.listener (/Users/wcj/dev/ormojo/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/wcj/dev/ormojo/node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

Probable cause is that the ESQuery flowtype is being treated as a revferenced identifier, but it is not contained in a structure that ESLint understands. This is probably an ESLint bug.

**Comment by wcjohnson** [comment]
Actual cause is ESLint and `babel-eslint` moving ahead to the Babel 7 api while we are on Babel 6. We cannot move our `babel-eslint` branch up to master until the rest of lightscript is on Babel 7.

Temporary workaround: use `eslint: '=4.8.0'` in package.json to force old eslint.

**Comment by wcjohnson** [comment]
No longer necessary with 4.0 linter redesign; closing.
